### ISSUE TITLE
Plugin no longer works with Sonarqube > 9.0

### ISSUE THREAD

**Issue by turekg** [cnescatlab/sonar-icode-cnes-plugin#81]
According to SonarQube's [Plugin Version Matrix](https://docs.sonarqube.org/latest/instance-administration/plugin-version-matrix/) version 2.0.2 should work with version 9.0. However I installed 9.1 today and the web interface fails. From web.log:
```
2021.08.30 17:04:03 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
org.sonar.server.exceptions.BadRequestException: Rule was removed: f77-rules:F77.DATA.Array
	at org.sonar.server.exceptions.BadRequestException.create(BadRequestException.java:57)
	at org.sonar.server.exceptions.BadRequestException.create(BadRequestException.java:61)
	at org.sonar.server.exceptions.BadRequestException.checkRequest(BadRequestException.java:44)
	at org.sonar.server.qualityprofile.RuleActivator.doActivate(RuleActivator.java:82)
	at org.sonar.server.qualityprofile.RuleActivator.activate(RuleActivator.java:77)
	at org.sonar.server.qualityprofile.BuiltInQProfileUpdateImpl.update(BuiltInQProfileUpdateImpl.java:73)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.update(RegisterQualityProfiles.java:132)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.lambda$start$1(RegisterQualityProfiles.java:93)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.start(RegisterQualityProfiles.java:88)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:49)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:87)
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:84)
	at org.sonar.server.platform.PlatformImpl.executeStartupTasks(PlatformImpl.java:198)
	at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$1(PlatformImpl.java:122)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:370)
	at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:122)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:354)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021.08.30 17:04:03 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
```
After I removed the plugin the web interface came up. Any chance this can be quickly solved? Thanx

**Comment by daluar** [comment]
Hi! This is still happening in v3.0.1 of the plugin with SonarQube 9.9 LTS
We would love to have this in our codebase :)

**Comment by lhimstedt** [comment]
We have the same problem. We want to use the plugin, but our SonarQube instance was set up on 9.9 LTS. Any estimations on this, @diegorodriguez31?

**Comment by diegorodriguez31** [comment]
> We have the same problem. We want to use the plugin, but our SonarQube instance was set up on 9.9 LTS. Could you give us an estimation on this, @diegorodriguez31?
> 
> We'll also check if we could create a fix, but since we're new to this package... 😄

We are currently working in this ! Next week should be done. Thanks

**Comment by daluar** [comment]
Hi @diegorodriguez31 ! thanks for looking into this. I was wondering if there has been any new updates on your side

**Comment by JeffPeters-1977** [comment]
@diegorodriguez31:
Hello.
Are you working to ensure that the new sonar-icode-cnes-plugin plugin version will also be compatible with SonarQube v10.0?
Thank you for your time!

**Comment by JeffPeters-1977** [comment]
Hello.

While we are greatly appreciative of the recent release of a new sonaricode plugin version 3.1.0 that is supported by SonarQube version 9.9 for Fortran, we remain interested in the community's support for a sonaricode plugin version that is compatible for SonarQube version 10.1.0.

Many thanks for your assistance!
